name: Bug report
description: Report an issue with the modpack in its unmodified state.
labels: bug
body:
- type: markdown
  attributes:
    value: |
      Before reporting an issue, [please search](https://github.com/OOrigamii/Flame/issues) to make sure it has not already been reported. 

- type: textarea
  attributes:
    label: Describe the bug
    description: Describe your issue.
  validations:
    required: true

- type: input
  attributes:
    label: Modpack version
    description: What version of the modpack are you using?
    placeholder: Version link
  validations:
    required: true

- type: checkboxes
  attributes:
    label: Confirm
    options:
      - label: This bug report is about an issue with the modpack itself, I have not modified the mods nor added any resource packs.
        required: true
    
- type: textarea
  attributes:
    label: Additional context
    description: Screenshots, video or any other information.
    placeholder: |
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
